// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkodwfyncoimuzlvbqio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrb2R3ZnluY29pbXV6bHZicWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDU4NzgsImV4cCI6MjA1OTQyMTg3OH0.voKEzKabB_jXE0NZgBFhwoC-nqmsXhFDYb3DNSRFZjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);